// Code generated by mockery v2.18.0. DO NOT EDIT.
// https://github.com/eminetto/api-o11y/blob/main/auth/user/mocks/UseCase.go

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

type UseCase struct {
	mock.Mock
}

func (_m *UseCase) ValidateUser(ctx context.Context, email string, password string) error {
	ret := _m.Called(ctx, email, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUseCase interface {
	mock.TestingT
	Cleanup(func())
}

func NewUseCase(t mockConstructorTestingTNewUseCase) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
